
version: 2.1

jobs:
  tests:
    docker:
      - image: circleci/node:12.13.1
    steps:
      - checkout
      - restore_cache:
          key: lib-dependencies-v1-{{ checksum "yarn.lock" }}
      - run:
          name: Instal dependencies
          command: |
            yarn --frozen-lockfile
      - save_cache:
          paths:
            - javascripts/node_modules
          key: lib-dependencies-v1-{{ checksum "yarn.lock" }}
      - run:
          name: Run Node Tests
          command: |
              yarn test -- --coverage
              yarn lint
              yarn build
              yarn size
  release:
    docker:
      - image: circleci/node:12.13.1
    steps:
      - checkout
      - restore_cache:
          key: lib-dependencies-v1-{{ checksum "yarn.lock" }}
      - run: yarn --frozen-lockfile
      - save_cache:
          paths:
            - javascripts/node_modules
          key: lib-dependencies-v1-{{ checksum "yarn.lock" }}
      - run:
          name: Publish
          command: |
              echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > .npmrc
              npm publish

workflows:
  version: 2
  cibuild:
    jobs:
      - tests
      - release:
          requires:
            - tests
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+){0,2}(\.snapshot)?/
